# Generated by Django 5.1.4 on 2024-12-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="tweets.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
